dist: xenial
language: python

python:
  - 3.7

addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3

install:
  - pip install -r requirements.txt
  - pip install -e .

before_script:
  - mv tests/data/.idb ~/.idb 

script:
  - cd tests
  - ./prepare_db_and_run_tests.sh
